# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Aditya Kumar
tagline:          'Aditya Kumar'
description:      'Data Scientist at Spiceworks working on NLP'
url:              http://aditya00kumar.github.io/
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Aditya Kumar'
  url:            https://github.com/aditya00kumar/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      aditya00kumar

google_analytics: UA-147707450-1

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version:          4.0.2
  repo:             https://github.com/aditya00kumar
